-- CreateEnum
CREATE TYPE "EscalationMode" AS ENUM ('live', 'priority', 'standard', 'selfResolving');

-- AlterTable
ALTER TABLE "Agent" ADD COLUMN "aiDeskEnabled" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "HandoffTicket" ADD COLUMN "routedTo" VARCHAR(16);
ALTER TABLE "HandoffTicket" ADD COLUMN "clusterId" UUID;
ALTER TABLE "HandoffTicket" ADD COLUMN "runbookId" UUID;
ALTER TABLE "HandoffTicket" ADD COLUMN "resolvedAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "TeamMemberProfile" (
    "id" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "role" VARCHAR(128) NOT NULL,
    "knowledgeAreas" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "maxConcurrent" INTEGER NOT NULL DEFAULT 5,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PK_TeamMemberProfile" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Runbook" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "steps" JSONB NOT NULL DEFAULT '[]',
    "triggerTopics" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "sourceTicketId" UUID,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PK_Runbook" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EscalationPolicy" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "urgencyLevel" "HandoffTicketUrgency" NOT NULL,
    "mode" "EscalationMode" NOT NULL DEFAULT 'standard',
    "slaMinutes" INTEGER,
    "routeToKnowledgeAreas" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PK_EscalationPolicy" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ResolutionCluster" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "topicEmbedding" TEXT,
    "templateResponse" TEXT NOT NULL,
    "ticketCount" INTEGER NOT NULL DEFAULT 0,
    "successRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "lastUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PK_ResolutionCluster" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClusterEntry" (
    "id" UUID NOT NULL,
    "clusterId" UUID NOT NULL,
    "ticketId" UUID NOT NULL,
    "resolution" TEXT NOT NULL,
    "wasSuccessful" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_ClusterEntry" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TeamMemberProfile_userId_key" ON "TeamMemberProfile"("userId");

-- CreateIndex
CREATE INDEX "IX_TeamMemberProfile_organizationId" ON "TeamMemberProfile"("organizationId");

-- CreateIndex
CREATE INDEX "IX_Runbook_organizationId" ON "Runbook"("organizationId");

-- CreateIndex
CREATE INDEX "IX_EscalationPolicy_organizationId" ON "EscalationPolicy"("organizationId");

-- CreateIndex
CREATE INDEX "IX_ResolutionCluster_organizationId" ON "ResolutionCluster"("organizationId");

-- CreateIndex
CREATE INDEX "IX_ClusterEntry_clusterId" ON "ClusterEntry"("clusterId");

-- CreateIndex
CREATE INDEX "IX_HandoffTicket_routedTo" ON "HandoffTicket"("routedTo");

-- AddForeignKey
ALTER TABLE "TeamMemberProfile" ADD CONSTRAINT "TeamMemberProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamMemberProfile" ADD CONSTRAINT "TeamMemberProfile_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Runbook" ADD CONSTRAINT "Runbook_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EscalationPolicy" ADD CONSTRAINT "EscalationPolicy_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ResolutionCluster" ADD CONSTRAINT "ResolutionCluster_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClusterEntry" ADD CONSTRAINT "ClusterEntry_clusterId_fkey" FOREIGN KEY ("clusterId") REFERENCES "ResolutionCluster"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HandoffTicket" ADD CONSTRAINT "HandoffTicket_clusterId_fkey" FOREIGN KEY ("clusterId") REFERENCES "ResolutionCluster"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HandoffTicket" ADD CONSTRAINT "HandoffTicket_runbookId_fkey" FOREIGN KEY ("runbookId") REFERENCES "Runbook"("id") ON DELETE SET NULL ON UPDATE CASCADE;
