ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "creditAutoReloadEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "creditAutoReloadThresholdCents" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "creditAutoReloadAmountCents" INTEGER NOT NULL DEFAULT 2000;

ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "creditAutoReloadEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "creditAutoReloadThresholdCents" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "creditAutoReloadAmountCents" INTEGER NOT NULL DEFAULT 2000;
