import type { EscalationMode, HandoffTicketUrgency } from '@prisma/client';

export type DeskRoutedTo = 'ai' | 'human';

export type ClusterItem = {
  id: string;
  title: string;
  pattern: string;
  issueType: string;
  description: string | null;
  templateResponse: string;
  ticketCount: number;
  successRate: number;
  lastUpdatedAt: string;
};

export type RunbookItem = {
  id: string;
  title: string;
  description: string | null;
  triggerTopics: string[];
  isAutoGenerated: boolean;
  reviewStatus: 'PENDING_REVIEW' | 'APPROVED';
  stepsCount: number;
  updatedAt: string;
};

export type EscalationPolicyItem = {
  id: string;
  name: string;
  urgencyLevel: HandoffTicketUrgency;
  mode: EscalationMode;
  slaMinutes: number | null;
  routeToKnowledgeAreas: string[];
  isDefault: boolean;
};

export type TeamProfileItem = {
  userId: string;
  name: string;
  image: string | null;
  email: string | null;
  role: string;
  knowledgeAreas: string[];
  maxConcurrent: number;
  currentTickets: number;
};

export type RunbookStep = {
  order: number;
  instruction: string;
};
