import * as Animated from 'lucide-animated';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const mappings = {
  ActivityIcon: 'ActivityIcon',
  AlertCircleIcon: 'BadgeAlertIcon',
  AlertTriangleIcon: 'BadgeAlertIcon',
  ArrowDownIcon: 'ArrowDownIcon',
  ArrowLeftIcon: 'ArrowLeftIcon',
  ArrowRight: 'ArrowRightIcon',
  ArrowRightIcon: 'ArrowRightIcon',
  ArrowUp: 'ArrowUpIcon',
  ArrowUpRight: 'ArrowUpRightIcon',
  ArrowUpRightIcon: 'ArrowUpRightIcon',
  BarChart3: 'ChartBarIncreasingIcon',
  BarChart3Icon: 'ChartBarIncreasingIcon',
  BellIcon: 'BellIcon',
  BlocksIcon: 'BlocksIcon',
  BoldIcon: 'BoldIcon',
  BookOpen: 'BookTextIcon',
  BookOpenIcon: 'BookTextIcon',
  Bot: 'BotIcon',
  BotIcon: 'BotIcon',
  Brain: 'BrainIcon',
  Building2: 'HomeIcon',
  BuildingIcon: 'HomeIcon',
  CalendarIcon: 'CalendarCheckIcon',
  Check: 'CheckIcon',
  CheckIcon: 'CheckIcon',
  CheckSquare2Icon: 'CheckCheckIcon',
  ChevronDown: 'ChevronDownIcon',
  ChevronDownIcon: 'ChevronDownIcon',
  ChevronLeft: 'ChevronLeftIcon',
  ChevronLeftIcon: 'ChevronLeftIcon',
  ChevronRight: 'ChevronRightIcon',
  ChevronRightIcon: 'ChevronRightIcon',
  ChevronsUpDownIcon: 'ChevronsUpDownIcon',
  ChevronUpIcon: 'ChevronUpIcon',
  CircleAlert: 'BadgeAlertIcon',
  CircleCheck: 'CircleCheckIcon',
  CircleUser: 'UserIcon',
  ClockIcon: 'ClockIcon',
  Code2: 'TerminalIcon',
  CodeIcon: 'TerminalIcon',
  Compass: 'CompassIcon',
  ComponentIcon: 'BoxesIcon',
  CopyIcon: 'CopyIcon',
  Cpu: 'CpuIcon',
  CreditCardIcon: 'CreditCardIcon',
  Database: 'DatabaseIcon',
  DumbbellIcon: 'BicepsFlexedIcon',
  ExternalLinkIcon: 'LinkIcon',
  EyeIcon: 'EyeIcon',
  EyeOffIcon: 'EyeOffIcon',
  FileIcon: 'FileTextIcon',
  FilePlus2Icon: 'FileCheck2Icon',
  FileTextIcon: 'FileTextIcon',
  Globe: 'EarthIcon',
  GlobeIcon: 'EarthIcon',
  GlobeLockIcon: 'LockKeyholeIcon',
  GraduationCap: 'GraduationCapIcon',
  GraduationCapIcon: 'GraduationCapIcon',
  GridIcon: 'LayoutGridIcon',
  HeadsetIcon: 'ConciergeBellIcon',
  HeartPulse: 'HeartPulseIcon',
  HomeIcon: 'HomeIcon',
  InfoIcon: 'CircleHelpIcon',
  ItalicIcon: 'ItalicIcon',
  KeyRoundIcon: 'KeyCircleIcon',
  Layers: 'LayersIcon',
  LayoutListIcon: 'ListIcon',
  Link2Icon: 'LinkIcon',
  Loader2: 'LoaderCircleIcon',
  Loader2Icon: 'LoaderCircleIcon',
  Lock: 'LockIcon',
  LockIcon: 'LockIcon',
  LockKeyholeIcon: 'LockKeyholeIcon',
  Mail: 'MailCheckIcon',
  MailIcon: 'MailCheckIcon',
  Menu: 'MenuIcon',
  MenuIcon: 'MenuIcon',
  MessageCircle: 'MessageCircleIcon',
  MessageCircleIcon: 'MessageCircleIcon',
  MessageSquare: 'MessageSquareIcon',
  Minus: 'DeleteIcon',
  MonitorIcon: 'MonitorCheckIcon',
  MoreHorizontalIcon: 'GripHorizontalIcon',
  NetworkIcon: 'RouteIcon',
  Paperclip: 'AttachFileIcon',
  PencilIcon: 'SquarePenIcon',
  PhoneIcon: 'PhoneIcon',
  PlaneIcon: 'AirplaneIcon',
  PlayIcon: 'PlayIcon',
  Plug: 'PlugZapIcon',
  PlugIcon: 'PlugZapIcon',
  Plus: 'PlusIcon',
  PlusIcon: 'PlusIcon',
  RadioIcon: 'RadioIcon',
  Rocket: 'RocketIcon',
  SearchIcon: 'SearchIcon',
  SettingsIcon: 'SettingsIcon',
  ShieldCheck: 'ShieldCheckIcon',
  ShieldIcon: 'ShieldCheckIcon',
  ShoppingBag: 'CartIcon',
  SlidersHorizontal: 'SlidersHorizontalIcon',
  SmileIcon: 'SmileIcon',
  Sparkles: 'SparklesIcon',
  SquareDashedKanbanIcon: 'FolderKanbanIcon',
  StarIcon: 'BookmarkIcon',
  StarOffIcon: 'BookmarkXIcon',
  StoreIcon: 'HomeIcon',
  ThumbsDown: 'DownvoteIcon',
  ThumbsUp: 'UpvoteIcon',
  Trash2Icon: 'DeleteIcon',
  TrashIcon: 'DeleteIcon',
  TriangleAlert: 'BadgeAlertIcon',
  TriangleAlertIcon: 'BadgeAlertIcon',
  UnderlineIcon: 'UnderlineIcon',
  UploadIcon: 'UploadIcon',
  User: 'UserIcon',
  UserIcon: 'UserIcon',
  UserPlus2Icon: 'UserRoundPlusIcon',
  UsersIcon: 'UsersIcon',
  WebhookIcon: 'WebhookIcon',
  X: 'XIcon',
  XIcon: 'XIcon'
};

const missing = Object.entries(mappings).filter(([, value]) => !Animated[value]);
if (missing.length) {
  console.error('Missing animated icons:', missing);
  process.exit(1);
}

const lines = [
  "'use client';",
  '',
  "import * as Animated from 'lucide-animated';",
  '',
  "import { createAnimatedIcon, type LucideIcon } from './icon-utils';",
  '',
  'export type { LucideIcon };',
  ''
];

for (const [exportName, sourceName] of Object.entries(mappings)) {
  lines.push(
    `export const ${exportName} = createAnimatedIcon(Animated.${sourceName});`
  );
}

writeFileSync(join(__dirname, 'src/icons.tsx'), `${lines.join('\n')}\n`);
console.log(`Generated ${Object.keys(mappings).length} icons`);
